[G-team] Thread 작성, 수정, 삭제 기능 추가
wecode-bootcamp-korea/48-1st-G-backend pull request #3
Opened 2023-08-15 05:56 UTC by ghj1

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
고객이 실시간으로 글을 작성하고 수정하고 삭제 할 수 있게 하기 위해 개발

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
실시간으로 유저들이 작성한 글을 확인하며 본인이 작성한 글을 수정하고 삭제할 수 있습니다. 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.
- 글 작성 기능 추가 
- 글 수정 기능 추가 
- 글 삭제 기능 추가 

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
- DB threads table에 글 내용 추가
<img width="602" alt="스크린샷 2023-08-15 14 54 08" src="https://github.com/wecode-bootcamp-korea/48-1st-G-backend/assets/90584168/85231cd5-80f4-49a2-b28f-fc98b5a56e4b">

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.
- layered pattern을 직접 응용해보면서 어떤 형태와 방향으로 진행 되는지 이해할 수 있었습니다. 

  <br />

2023-08-16 01:39 UTC, kyeongraekim requested changes

2023-08-16 01:39 UTC, kyeongraekim commented on db/migrations/20230814072350_users.sql
> +DROP TABLE users;
- Thread 수정 삭제에 대한 내용만이 있어야 하는데, 현재 pr로 올라온 다른 내용과 함께 해당 마이그레이션 파일이 올라와있네요. 
- 푸시 및 main 반영을 의도하신 것이라면, 다른 피알에 올려드린 또다른 리뷰를 참고해주시고, 그것이 아니라면 해당 내용은 본 브랜치에서 삭제하여주세요!
- 아마 push를 하시기전 pull을 생략하여 나오신 결과처럼 보여집니다!

2023-08-16 01:39 UTC, kyeongraekim commented on src/controllers/threads.controller.js
> +//thread 작성
- 코드 독해로 의미파악이 가능한 내용은 꼭 푸시전 삭제하여주세요!

2023-08-16 01:39 UTC, kyeongraekim commented on src/controllers/threads.controller.js
> +const threadUp = async (req, res) => {
- threadUp은 실무 웹 개발 코드에서의 변수명으로는 적절치 않아 보이는 내용입니다.
- uploadThread와 같이 올바른 동사 + 목적어의 형태의 워딩을 사용하여 정확히 어떠한 의미를 지니고 있는 레이어드 패턴 내 컨트롤러 모듈인지 명시하여 주세요!

2023-08-16 01:39 UTC, kyeongraekim commented on src/controllers/threads.controller.js
> +const threadMod = async (req, res) => {
- 해당 내용도 마찬가지 입니다!~

2023-08-16 01:39 UTC, kyeongraekim commented on src/services/auth.service.js
> +    err.statusCode = 400;
- Thread 게시글을 CRUD 하는 내용에 현재, 유저 관련 코드가 혼재되어서 올라와있습니다.
- 이는 엄격한 브랜치 분리관리의 실패를 의미하며, 실무 코드에서는 절대 주의해야할 실수 사항입니다.
- 내가 의도한 독립된 기능의 브랜치 소스코드가, 올바른 브랜치에 놓일 수 있도록 명심해주시고, 수정하여 재푸시해주세요!

2023-08-17 07:06 UTC, ghj1 commented on db/migrations/20230814072350_users.sql
> +DROP TABLE users;
해당 브랜치로 모든 내용 함께 올리고 이전 브랜치들은 삭제 처리 하겠습니다!

2023-08-17 07:10 UTC, ghj1 commented
모든 내용 수정하여 업데이트 했습니다! 이전 수정 요청하신 내용 다 수정하여 재확인 부탁드립니다!

2023-08-17 08:09 UTC, ghj1 commented
수정할 부분이 있어 수정 후 올렸습니다! 확인 부탁드립니다!

2023-08-17 13:14 UTC, ghj1 reviewed
G-team comments 기능과 comments list 기능 추가 구현 완료해 재업데이트 합니다!

2023-08-17 15:49 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-17 15:49 UTC, merged